### ISSUE TITLE
the web app is not working!

### ISSUE THREAD

**Issue by adouz** [encap/coderush#5]
https://coderush.xyz/ is showing a blank page
this what I found in console:
`Loading failed for the <script> with source “https://coderushcdn.ddns.net/js/chunk-vendors.js”. coderush.xyz:5:1`
`Loading failed for the <script> with source “https://coderushcdn.ddns.net/js/app.js”.`

**Comment by encap** [comment]
Thank you. I was updating CDN DNS and i took a while.
