### ISSUE TITLE
⌥ restart the challenge

### ISSUE THREAD

**Issue by dawalberto** [encap/coderush#6]
On Mac OS the key ⌥ restart the challenge. Important issue because we need this key to write `[`, `]`, `{`, `}`

**Comment by encap** [comment]
OMG on Windows ALT key does the same. How I didn't noticed that

**Comment by encap** [comment]
`
  <mail=n
    :key="resetSelfKey"
    :class="{wide: stats }"
    **@keydown.alt="resetSelf"**
  >
`
Some left over debug code coused this
