### ISSUE TITLE
Feature request: add a code correction/navigation game

### ISSUE THREAD

**Issue by petko10** [encap/coderush#61]
Hi, the app is great, props to the developers! 
I've been searching for a while for a way to practice my code navigation skills in a practice environment (as opposed to when writing code, when I have other things on my mind). 
It would be trickier to implement than the typing exercises, since people have their own setups and IDE-s have their own features. Also gathering data about plausible corrections will be trickier than gathering code (though there is some avenue for automation via analyzing commits). Still it would be such a great thing to have, since code/navigation correction consists a lot more of the workflow than pure continuous typing.

**Comment by encap** [comment]
CodeRush was actually developed by a single person (me :D), and I moved to making other projects. Also, looking back, the code base here is such a mess, that I don't want to add any new features before a refactor. That said I hope you will understand that this feature is to complex and time consuming to implement. You can of course fork this repo.

**Comment by petko10** [comment]
Totally understandable, thanks for the reply!

**Comment by encap** [comment]
Also looking back, I should probably add a note for the users that they should focus on using the autocompletion and other things apart from, as you have said, pure continues typing.

**Comment by petko10** [comment]
Yup. Still typing (even without autocomplete) is pretty important. But on that note - coding exercise apps probably should be implemented as IDE extensions, since there are too many specifics that otherwise need to be implemented to emulate shortcuts and IDE behavior.
