### ISSUE TITLE
Azerty keyboard "ALT-GR" key

### ISSUE THREAD

**Issue by Orkad** [encap/coderush#7]
Hello there,

i try to make my best core on this. But when i wanna type a bracket (must use the "alt gr" key on my Azerty keyboard) things goes bad and i can't type any other characters after i pressed the key).

**Comment by encap** [comment]
Alt gr is weird becouse it generates two keydown events. Control right and next Alt right. I will look into that.

**Comment by encap** [comment]
String from ev.key is passed into the editor so any special key must be catched and handled separately before that which wasn't the case for AltGraph. Thank you.

**Comment by encap** [comment]
I hope my fix won't have any other side effects in your keyboard layout.
